/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepoRouteImport } from './routes/$repo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoIndexRouteImport } from './routes/$repo/index'
import { Route as AuthSelectIdentityRouteImport } from './routes/auth/select-identity'
import { Route as RepoIssuesRouteImport } from './routes/$repo/_issues'
import { Route as RepoCommitHashRouteImport } from './routes/$repo/commit/$hash'
import { Route as RepoIssuesIssuesIndexRouteImport } from './routes/$repo/_issues/issues/index'
import { Route as RepoIssuesUserIdRouteImport } from './routes/$repo/_issues/user/$id'
import { Route as RepoIssuesIssuesNewRouteImport } from './routes/$repo/_issues/issues/new'
import { Route as RepoIssuesIssuesIdRouteImport } from './routes/$repo/_issues/issues/$id'

const RepoRoute = RepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoIndexRoute = RepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepoRoute,
} as any)
const AuthSelectIdentityRoute = AuthSelectIdentityRouteImport.update({
  id: '/auth/select-identity',
  path: '/auth/select-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoIssuesRoute = RepoIssuesRouteImport.update({
  id: '/_issues',
  getParentRoute: () => RepoRoute,
} as any)
const RepoCommitHashRoute = RepoCommitHashRouteImport.update({
  id: '/commit/$hash',
  path: '/commit/$hash',
  getParentRoute: () => RepoRoute,
} as any)
const RepoIssuesIssuesIndexRoute = RepoIssuesIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => RepoIssuesRoute,
} as any)
const RepoIssuesUserIdRoute = RepoIssuesUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => RepoIssuesRoute,
} as any)
const RepoIssuesIssuesNewRoute = RepoIssuesIssuesNewRouteImport.update({
  id: '/issues/new',
  path: '/issues/new',
  getParentRoute: () => RepoIssuesRoute,
} as any)
const RepoIssuesIssuesIdRoute = RepoIssuesIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => RepoIssuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$repo': typeof RepoIssuesRouteWithChildren
  '/auth/select-identity': typeof AuthSelectIdentityRoute
  '/$repo/': typeof RepoIndexRoute
  '/$repo/commit/$hash': typeof RepoCommitHashRoute
  '/$repo/issues/$id': typeof RepoIssuesIssuesIdRoute
  '/$repo/issues/new': typeof RepoIssuesIssuesNewRoute
  '/$repo/user/$id': typeof RepoIssuesUserIdRoute
  '/$repo/issues/': typeof RepoIssuesIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$repo': typeof RepoIndexRoute
  '/auth/select-identity': typeof AuthSelectIdentityRoute
  '/$repo/commit/$hash': typeof RepoCommitHashRoute
  '/$repo/issues/$id': typeof RepoIssuesIssuesIdRoute
  '/$repo/issues/new': typeof RepoIssuesIssuesNewRoute
  '/$repo/user/$id': typeof RepoIssuesUserIdRoute
  '/$repo/issues': typeof RepoIssuesIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$repo': typeof RepoRouteWithChildren
  '/$repo/_issues': typeof RepoIssuesRouteWithChildren
  '/auth/select-identity': typeof AuthSelectIdentityRoute
  '/$repo/': typeof RepoIndexRoute
  '/$repo/commit/$hash': typeof RepoCommitHashRoute
  '/$repo/_issues/issues/$id': typeof RepoIssuesIssuesIdRoute
  '/$repo/_issues/issues/new': typeof RepoIssuesIssuesNewRoute
  '/$repo/_issues/user/$id': typeof RepoIssuesUserIdRoute
  '/$repo/_issues/issues/': typeof RepoIssuesIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$repo'
    | '/auth/select-identity'
    | '/$repo/'
    | '/$repo/commit/$hash'
    | '/$repo/issues/$id'
    | '/$repo/issues/new'
    | '/$repo/user/$id'
    | '/$repo/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$repo'
    | '/auth/select-identity'
    | '/$repo/commit/$hash'
    | '/$repo/issues/$id'
    | '/$repo/issues/new'
    | '/$repo/user/$id'
    | '/$repo/issues'
  id:
    | '__root__'
    | '/'
    | '/$repo'
    | '/$repo/_issues'
    | '/auth/select-identity'
    | '/$repo/'
    | '/$repo/commit/$hash'
    | '/$repo/_issues/issues/$id'
    | '/$repo/_issues/issues/new'
    | '/$repo/_issues/user/$id'
    | '/$repo/_issues/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoRoute: typeof RepoRouteWithChildren
  AuthSelectIdentityRoute: typeof AuthSelectIdentityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$repo': {
      id: '/$repo'
      path: '/$repo'
      fullPath: '/$repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$repo/': {
      id: '/$repo/'
      path: '/'
      fullPath: '/$repo/'
      preLoaderRoute: typeof RepoIndexRouteImport
      parentRoute: typeof RepoRoute
    }
    '/auth/select-identity': {
      id: '/auth/select-identity'
      path: '/auth/select-identity'
      fullPath: '/auth/select-identity'
      preLoaderRoute: typeof AuthSelectIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$repo/_issues': {
      id: '/$repo/_issues'
      path: ''
      fullPath: '/$repo'
      preLoaderRoute: typeof RepoIssuesRouteImport
      parentRoute: typeof RepoRoute
    }
    '/$repo/commit/$hash': {
      id: '/$repo/commit/$hash'
      path: '/commit/$hash'
      fullPath: '/$repo/commit/$hash'
      preLoaderRoute: typeof RepoCommitHashRouteImport
      parentRoute: typeof RepoRoute
    }
    '/$repo/_issues/issues/': {
      id: '/$repo/_issues/issues/'
      path: '/issues'
      fullPath: '/$repo/issues/'
      preLoaderRoute: typeof RepoIssuesIssuesIndexRouteImport
      parentRoute: typeof RepoIssuesRoute
    }
    '/$repo/_issues/user/$id': {
      id: '/$repo/_issues/user/$id'
      path: '/user/$id'
      fullPath: '/$repo/user/$id'
      preLoaderRoute: typeof RepoIssuesUserIdRouteImport
      parentRoute: typeof RepoIssuesRoute
    }
    '/$repo/_issues/issues/new': {
      id: '/$repo/_issues/issues/new'
      path: '/issues/new'
      fullPath: '/$repo/issues/new'
      preLoaderRoute: typeof RepoIssuesIssuesNewRouteImport
      parentRoute: typeof RepoIssuesRoute
    }
    '/$repo/_issues/issues/$id': {
      id: '/$repo/_issues/issues/$id'
      path: '/issues/$id'
      fullPath: '/$repo/issues/$id'
      preLoaderRoute: typeof RepoIssuesIssuesIdRouteImport
      parentRoute: typeof RepoIssuesRoute
    }
  }
}

interface RepoIssuesRouteChildren {
  RepoIssuesIssuesIdRoute: typeof RepoIssuesIssuesIdRoute
  RepoIssuesIssuesNewRoute: typeof RepoIssuesIssuesNewRoute
  RepoIssuesUserIdRoute: typeof RepoIssuesUserIdRoute
  RepoIssuesIssuesIndexRoute: typeof RepoIssuesIssuesIndexRoute
}

const RepoIssuesRouteChildren: RepoIssuesRouteChildren = {
  RepoIssuesIssuesIdRoute: RepoIssuesIssuesIdRoute,
  RepoIssuesIssuesNewRoute: RepoIssuesIssuesNewRoute,
  RepoIssuesUserIdRoute: RepoIssuesUserIdRoute,
  RepoIssuesIssuesIndexRoute: RepoIssuesIssuesIndexRoute,
}

const RepoIssuesRouteWithChildren = RepoIssuesRoute._addFileChildren(
  RepoIssuesRouteChildren,
)

interface RepoRouteChildren {
  RepoIssuesRoute: typeof RepoIssuesRouteWithChildren
  RepoIndexRoute: typeof RepoIndexRoute
  RepoCommitHashRoute: typeof RepoCommitHashRoute
}

const RepoRouteChildren: RepoRouteChildren = {
  RepoIssuesRoute: RepoIssuesRouteWithChildren,
  RepoIndexRoute: RepoIndexRoute,
  RepoCommitHashRoute: RepoCommitHashRoute,
}

const RepoRouteWithChildren = RepoRoute._addFileChildren(RepoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoRoute: RepoRouteWithChildren,
  AuthSelectIdentityRoute: AuthSelectIdentityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
