/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepoRouteImport } from './routes/$repo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoIndexRouteImport } from './routes/$repo/index'
import { Route as AuthSelectIdentityRouteImport } from './routes/auth/select-identity'
import { Route as RepoIssuesIndexRouteImport } from './routes/$repo/issues/index'
import { Route as RepoUserIdRouteImport } from './routes/$repo/user/$id'
import { Route as RepoIssuesNewRouteImport } from './routes/$repo/issues/new'
import { Route as RepoIssuesIdRouteImport } from './routes/$repo/issues/$id'
import { Route as RepoCommitHashRouteImport } from './routes/$repo/commit/$hash'

const RepoRoute = RepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoIndexRoute = RepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepoRoute,
} as any)
const AuthSelectIdentityRoute = AuthSelectIdentityRouteImport.update({
  id: '/auth/select-identity',
  path: '/auth/select-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoIssuesIndexRoute = RepoIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => RepoRoute,
} as any)
const RepoUserIdRoute = RepoUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => RepoRoute,
} as any)
const RepoIssuesNewRoute = RepoIssuesNewRouteImport.update({
  id: '/issues/new',
  path: '/issues/new',
  getParentRoute: () => RepoRoute,
} as any)
const RepoIssuesIdRoute = RepoIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => RepoRoute,
} as any)
const RepoCommitHashRoute = RepoCommitHashRouteImport.update({
  id: '/commit/$hash',
  path: '/commit/$hash',
  getParentRoute: () => RepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$repo': typeof RepoRouteWithChildren
  '/auth/select-identity': typeof AuthSelectIdentityRoute
  '/$repo/': typeof RepoIndexRoute
  '/$repo/commit/$hash': typeof RepoCommitHashRoute
  '/$repo/issues/$id': typeof RepoIssuesIdRoute
  '/$repo/issues/new': typeof RepoIssuesNewRoute
  '/$repo/user/$id': typeof RepoUserIdRoute
  '/$repo/issues/': typeof RepoIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/select-identity': typeof AuthSelectIdentityRoute
  '/$repo': typeof RepoIndexRoute
  '/$repo/commit/$hash': typeof RepoCommitHashRoute
  '/$repo/issues/$id': typeof RepoIssuesIdRoute
  '/$repo/issues/new': typeof RepoIssuesNewRoute
  '/$repo/user/$id': typeof RepoUserIdRoute
  '/$repo/issues': typeof RepoIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$repo': typeof RepoRouteWithChildren
  '/auth/select-identity': typeof AuthSelectIdentityRoute
  '/$repo/': typeof RepoIndexRoute
  '/$repo/commit/$hash': typeof RepoCommitHashRoute
  '/$repo/issues/$id': typeof RepoIssuesIdRoute
  '/$repo/issues/new': typeof RepoIssuesNewRoute
  '/$repo/user/$id': typeof RepoUserIdRoute
  '/$repo/issues/': typeof RepoIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$repo'
    | '/auth/select-identity'
    | '/$repo/'
    | '/$repo/commit/$hash'
    | '/$repo/issues/$id'
    | '/$repo/issues/new'
    | '/$repo/user/$id'
    | '/$repo/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/select-identity'
    | '/$repo'
    | '/$repo/commit/$hash'
    | '/$repo/issues/$id'
    | '/$repo/issues/new'
    | '/$repo/user/$id'
    | '/$repo/issues'
  id:
    | '__root__'
    | '/'
    | '/$repo'
    | '/auth/select-identity'
    | '/$repo/'
    | '/$repo/commit/$hash'
    | '/$repo/issues/$id'
    | '/$repo/issues/new'
    | '/$repo/user/$id'
    | '/$repo/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoRoute: typeof RepoRouteWithChildren
  AuthSelectIdentityRoute: typeof AuthSelectIdentityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$repo': {
      id: '/$repo'
      path: '/$repo'
      fullPath: '/$repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$repo/': {
      id: '/$repo/'
      path: '/'
      fullPath: '/$repo/'
      preLoaderRoute: typeof RepoIndexRouteImport
      parentRoute: typeof RepoRoute
    }
    '/auth/select-identity': {
      id: '/auth/select-identity'
      path: '/auth/select-identity'
      fullPath: '/auth/select-identity'
      preLoaderRoute: typeof AuthSelectIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$repo/issues/': {
      id: '/$repo/issues/'
      path: '/issues'
      fullPath: '/$repo/issues/'
      preLoaderRoute: typeof RepoIssuesIndexRouteImport
      parentRoute: typeof RepoRoute
    }
    '/$repo/user/$id': {
      id: '/$repo/user/$id'
      path: '/user/$id'
      fullPath: '/$repo/user/$id'
      preLoaderRoute: typeof RepoUserIdRouteImport
      parentRoute: typeof RepoRoute
    }
    '/$repo/issues/new': {
      id: '/$repo/issues/new'
      path: '/issues/new'
      fullPath: '/$repo/issues/new'
      preLoaderRoute: typeof RepoIssuesNewRouteImport
      parentRoute: typeof RepoRoute
    }
    '/$repo/issues/$id': {
      id: '/$repo/issues/$id'
      path: '/issues/$id'
      fullPath: '/$repo/issues/$id'
      preLoaderRoute: typeof RepoIssuesIdRouteImport
      parentRoute: typeof RepoRoute
    }
    '/$repo/commit/$hash': {
      id: '/$repo/commit/$hash'
      path: '/commit/$hash'
      fullPath: '/$repo/commit/$hash'
      preLoaderRoute: typeof RepoCommitHashRouteImport
      parentRoute: typeof RepoRoute
    }
  }
}

interface RepoRouteChildren {
  RepoIndexRoute: typeof RepoIndexRoute
  RepoCommitHashRoute: typeof RepoCommitHashRoute
  RepoIssuesIdRoute: typeof RepoIssuesIdRoute
  RepoIssuesNewRoute: typeof RepoIssuesNewRoute
  RepoUserIdRoute: typeof RepoUserIdRoute
  RepoIssuesIndexRoute: typeof RepoIssuesIndexRoute
}

const RepoRouteChildren: RepoRouteChildren = {
  RepoIndexRoute: RepoIndexRoute,
  RepoCommitHashRoute: RepoCommitHashRoute,
  RepoIssuesIdRoute: RepoIssuesIdRoute,
  RepoIssuesNewRoute: RepoIssuesNewRoute,
  RepoUserIdRoute: RepoUserIdRoute,
  RepoIssuesIndexRoute: RepoIssuesIndexRoute,
}

const RepoRouteWithChildren = RepoRoute._addFileChildren(RepoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoRoute: RepoRouteWithChildren,
  AuthSelectIdentityRoute: AuthSelectIdentityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
